FROM osrf/ros:foxy-desktop
ENV ROS_DISTRO foxy

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        git \
        build-essential \
        cmake \
        byobu \
        vim \
        wget \
        unzip \
        libeigen3-dev \
        python3-colcon-common-extensions \
        libopencv-dev \
        ros-$ROS_DISTRO-joy-linux \
        ros-$ROS_DISTRO-image-geometry && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Install realsense2 ros wrapper
RUN apt-get update && apt-get install -y ros-$ROS_DISTRO-realsense2-camera

# Install image compression package
RUN apt-get install -y \
ros-${ROS_DISTRO}-image-transport \
ros-${ROS_DISTRO}-image-transport-plugins

WORKDIR /ros2_ws
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /root/.bashrc
# ENV ROS_DOMAIN_ID 1

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]