octomap_server:
  ros__parameters:
    resolution: 0.15
    frame_id: map
    base_frame_id: base_link
    height_map: True
    colored_map: True
    color_factor: 0.8
    filter_ground: False
    filter_speckles: False
    ground_filter/distance: 0.1
    ground_filter/angle: 0.15
    ground_filter/plane_distance: 0.1
    compress_map: True
    incremental_2D_projection: False
    sensor_model/max_range: -1.0
    sensor_model/hit: 0.7
    sensor_model/miss: 0.4
    sensor_model/min: 0.12
    sensor_model/max: 0.97
    color/r: 0.0
    color/g: 0.0
    color/b: 1.0
    color/a: 1.0
    color_free/r: 0.0
    color_free/g: 1.0
    color_free/b: 0.0
    color_free/a: 1.0
    publish_free_space: False
